### ISSUE TITLE
dashboard breaks when ansible inventory_hostname is in FQDN form

### ISSUE THREAD

**Issue by bmorris53** [nbentoumi/ansibledb#1]
I'm not sure if this is a problem with the callback plugin or with the server code.  I suspect the plugin.

I have this running in a k3s multi-master cluster.

I have Ansible AWX running in an adjacent namespace in the same cluster.

In my Ansible AWX project I am including the callback_plugins directory with the plugin, an inventory playbook, and an ansible.cfg file:

```
├── ansible.cfg
├── callback_plugins
│   └── ansibledb.py
├── cmdb_builder.yaml

[defaults]
callbacks_enabled = ansibledb
callback_whitelist = ansibledb
[callback_ansibledb]
url = 'http://ansibledb.ansibledb.svc.cluster.local:8080'
verify_certs = 0
enable_facts_caching = 1
```

When accessing the dashboard I get a 500 error:

```
[2023-10-04 17:20:17,911] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask_restx/api.py", line 674, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/ansibledb.py", line 321, in dashboard
    stat = {key:{'status':res[key]['ansible_reports']['status']}}
KeyError: 'ansible_reports'
```

That points to this code in def dashboard():

```
        project = {"_id":0}
        cursor = servers.find(query,project)
        result = list(cursor)
        summary=[]
        for res in result:
            report_time = res['ansible_reports']['report_time']
            sum = {}
            for key in res.keys():
                if key!='summary' and key!='ansible_reports':
                    stat = {key:{'status':res[key]['ansible_reports']['status']}}
                    sum = {**sum, **stat}
            summary.append({'report_time':report_time,'summary':sum})
```

Checking the data obtained from the mongodb query I see this for every host (Scrubbed for obvious reasons):

```
[{'ansible_reports': {'report_time': '2023-10-03 21:48:05+00:00'}, 'host-01': {'example': {'com': {'ansible_reports': {'hostname': 'host-01.example.com', 'report_time': '2023-10-03 21:48:05+00:00', 'status': {'ok': 10, 'failed': 0, 'unreachable': 0, 'changed': 0, 'skipped': 9, 'rescued': 0, 'ignored': 0}
```

So that stat line is not looking deep enough in the nested list because for some reason the document in mongo db has extra keys after the first key.

**Comment by nbentoumi** [comment]
Hi @bmorris53 ,

I was able to reproduce the issue and the fact that I've used hostname as key , once inserted to mongoDB , this got converted to dict.

I have Update the callback plugin to use short name instead fqdn, can you please clean up you mongoDB and try with new version of callback plugin ?

Regards

**Comment by bmorris53** [comment]
Confirmed this fixed the issue!  Thank you @nbentoumi!
